apiVersion: v1
kind: Service
metadata:
  name: personal-website-service
spec:
  selector:
    app: personal-website
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-deployment
  labels:
    app: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: personal-website
          image: ghcr.io/jordansimsmith/personal-website:32895442120cde1001ab38076041ea0898a3656d
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-github-secret
