apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: common-letsencrypt-production-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jordansimsmith@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-secret
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: common-letsencrypt-staging-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jordansimsmith@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-secret
    solvers:
      - http01:
          ingress:
            class: nginx
