apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pgsql-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: common-pgsql-service
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: common-pgsql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: common-pgsql-statefulset
spec:
  selector:
    matchLabels:
      app: common-pgsql
  serviceName: common-pgsql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: common-pgsql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: common-pgsql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-pgsql-secret
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: common-pgsql-vol
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: common-pgsql-vol
          persistentVolumeClaim:
            claimName: common-pgsql-pvc
