apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: jordansimsmith.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: football-subscriber.jordansimsmith.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: football-subscriber-client-service
                port:
                  number: 3000
    - host: api.football-subscriber.jordansimsmith.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: football-subscriber-server-service
                port:
                  number: 80
