apiVersion: v1
kind: Service
metadata:
  name: price-tracker-server-service
spec:
  selector:
    app: price-tracker-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracker-server-deployment
  labels:
    app: price-tracker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-tracker-server
  template:
    metadata:
      labels:
        app: price-tracker-server
    spec:
      containers:
        - name: price-tracker-server
          image: ghcr.io/jordansimsmith/price-tracker-server:0ec05cac71e293fc3268b2ced410293cd5bf5ebc
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__PriceTracker
              valueFrom:
                secretKeyRef:
                  name: price-tracker-secret
                  key: price-tracker-connection-string
            - name: ConnectionStrings__PriceTrackerHangfire
              valueFrom:
                secretKeyRef:
                  name: price-tracker-secret
                  key: hangfire-connection-string
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: price-tracker-secret
                  key: sendgrid-apikey
            - name: Hangfire__Password
              valueFrom:
                secretKeyRef:
                  name: price-tracker-secret
                  key: hangfire-password
            - name: OpenTelemetry__Endpoint
              value: http://common-telemetry-collector-service:4317
      imagePullSecrets:
        - name: docker-github-secret
