apiVersion: v1
kind: Service
metadata:
  name: football-subscriber-server-service
spec:
  selector:
    app: football-subscriber-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-subscriber-server-deployment
  labels:
    app: football-subscriber-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-subscriber-server
  template:
    metadata:
      labels:
        app: football-subscriber-server
    spec:
      containers:
        - name: football-subscriber-server
          image: ghcr.io/jordansimsmith/football-subscriber-server:f875c5530d5a4a26756fb768278b591896823b28
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__FootballSubscriber
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: football-subscriber-connection-string
            - name: ConnectionStrings__Hangfire
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: hangfire-connection-string
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: sendgrid-apikey
            - name: Auth0__ManagementClientId
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-management-client-id
            - name: Auth0__ManagementClientSecret
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-management-client-secret
            - name: Hangfire__Password
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: hangfire-password
            - name: OpenTelemetry__Endpoint
              value: http://common-telemetry-collector-service:4317
          resources:
            requests:
              memory: 128M
            limits:
              memory: 256M
      imagePullSecrets:
        - name: docker-github-secret
