apiVersion: v1
kind: Service
metadata:
  name: football-subscriber-server-service
spec:
  selector:
    app: football-subscriber-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-subscriber-server-deployment
  labels:
    app: football-subscriber-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-subscriber-server
  template:
    metadata:
      labels:
        app: football-subscriber-server
    spec:
      containers:
        - name: football-subscriber-server
          image: docker.pkg.github.com/jordansimsmith/football-subscriber/football-subscriber-server:183d859e4b7eb67e45ed101c4680253ffbc5ac8d
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__FootballSubscriber
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: football-subscriber-connection-string
            - name: ConnectionStrings__Hangfire
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: hangfire-connection-string
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: sendgrid-apikey
            - name: Auth0__ManagementClientId
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-management-client-id
            - name: Auth0__ManagementClientSecret
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-management-client-secret
      imagePullSecrets:
        - name: docker-github-secret
