apiVersion: v1
kind: Service
metadata:
  name: football-subscriber-client-service
spec:
  selector:
    app: football-subscriber-client
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-subscriber-client-deployment
  labels:
    app: football-subscriber-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-subscriber-client
  template:
    metadata:
      labels:
        app: football-subscriber-client
    spec:
      containers:
        - name: football-subscriber-client
          image: ghcr.io/jordansimsmith/football-subscriber-client:f875c5530d5a4a26756fb768278b591896823b28
          ports:
            - containerPort: 3000
          env:
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-secret
            - name: AUTH0_BASE_URL
              value: https://football-subscriber.jordansimsmith.com
            - name: AUTH0_ISSUER_BASE_URL
              value: https://football-subscriber.au.auth0.com
            - name: AUTH0_CLIENT_ID
              value: Mb8VqIoDpVDZjMNPKcbNJvpNsEj3ZjuY
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: football-subscriber-secret
                  key: auth0-client-secret
            - name: AUTH0_AUDIENCE
              value: https://api.football-subscriber.jordansimsmith.com
      imagePullSecrets:
        - name: docker-github-secret
