apiVersion: v1
kind: Service
metadata:
  name: immersion-tracker-server-service
spec:
  selector:
    app: immersion-tracker-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immersion-tracker-server-deployment
  labels:
    app: immersion-tracker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immersion-tracker-server
  template:
    metadata:
      labels:
        app: immersion-tracker-server
    spec:
      containers:
        - name: immersion-tracker-server
          image: ghcr.io/jordansimsmith/immersion-tracker-server:f6eb71d617cca00ed718eec52b5e93078cbce2fa
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://common-pgsql-service:5432/immersion_tracker?createDatabaseIfNotExist=true
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immersion-tracker-secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-password
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immersion-tracker-secret
                  key: api-username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immersion-tracker-secret
                  key: api-password
          resources:
            requests:
              memory: 100M
            limits:
              memory: 200M
      imagePullSecrets:
        - name: docker-github-secret
