apiVersion: v1
kind: Service
metadata:
  name: subfootball-tracker-server-service
spec:
  selector:
    app: subfootball-tracker-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subfootball-tracker-server-deployment
  labels:
    app: subfootball-tracker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subfootball-tracker-server
  template:
    metadata:
      labels:
        app: subfootball-tracker-server
    spec:
      containers:
        - name: subfootball-tracker-server
          image: ghcr.io/jordansimsmith/subfootball-tracker-server:5497b80746d2004df240dfb1d50af11b49d1d92d
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-password
            - name: SEND_GRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: sendgrid-apikey
          resources:
            requests:
              memory: 100M
            limits:
              memory: 200M
      imagePullSecrets:
        - name: docker-github-secret
