apiVersion: v1
kind: Service
metadata:
  name: subfootball-tracker-server-service
spec:
  selector:
    app: subfootball-tracker-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subfootball-tracker-server-deployment
  labels:
    app: subfootball-tracker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subfootball-tracker-server
  template:
    metadata:
      labels:
        app: subfootball-tracker-server
    spec:
      containers:
        - name: subfootball-tracker-server
          image: ghcr.io/jordansimsmith/subfootball-tracker-server:437c2ae2eb8e89e5158625504f303e0780cbecc0
          ports:
            - containerPort: 80
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://common-telemetry-collector-service:4317
            - name: DATABASE_URL
              value: jdbc:postgresql://common-pgsql-service:5432/subfootball_tracker?createDatabaseIfNotExist=true
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: database-password
            - name: SEND_GRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: subfootball-tracker-secret
                  key: sendgrid-apikey
          resources:
            requests:
              memory: 100M
            limits:
              memory: 300M
      imagePullSecrets:
        - name: docker-github-secret
