apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archie-trader-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: archie-trader-service
spec:
  selector:
    app: archie-trader
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archie-trader-statefulset
spec:
  selector:
    matchLabels:
      app: archie-trader
  serviceName: archie-trader-service
  replicas: 1
  template:
    metadata:
      labels:
        app: archie-trader
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: archie-trader
          image: ghcr.io/jordansimsmith/archie-trader:e1c2629c1bf7276e36fb9bda7fff673474aa2db9
          env:
            - name: ExternalReporting__Host
              value: common-rabbitmq-service
            - name: ExternalReporting__Username
              valueFrom:
                secretKeyRef:
                  name: archie-trader-secret
                  key: rabbitmq-username
            - name: ExternalReporting__Password
              valueFrom:
                secretKeyRef:
                  name: archie-trader-secret
                  key: rabbitmq-password
            - name: Trading__VirtualBalancesFilePath
              value: ./data/virtual_balances.json
          volumeMounts:
            - name: archie-trader-vol
              mountPath: /app/data
          resources:
            requests:
              memory: 100M
            limits:
              memory: 200M
      volumes:
        - name: archie-trader-vol
          persistentVolumeClaim:
            claimName: archie-trader-pvc
      imagePullSecrets:
        - name: docker-github-secret
